// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package sqlc

import (
	"context"
	"time"
)

const listUpcomingMatchesByUser = `-- name: ListUpcomingMatchesByUser :many
SELECT
    m.id,
    m.kickoff,
    m.stadium,
    m.city,
    m.stage,
    home.id       AS home_id,
    home.name     AS home_name,
    home.flag_url AS home_flag_url,
    home.code     AS home_code,
    away.id       AS away_id,
    away.name     AS away_name,
    away.flag_url AS away_flag_url,
    away.code     AS away_code
FROM matches m
JOIN national_teams home ON home.id = m.home_team_id
JOIN national_teams away ON away.id = m.away_team_id
WHERE m.kickoff > ?1
  AND (
        m.home_team_id IN (SELECT national_team_id FROM user_national_teams WHERE user_national_teams.user_id = ?2)
     OR m.away_team_id IN (SELECT national_team_id FROM user_national_teams WHERE user_national_teams.user_id = ?2)
  )
ORDER BY m.kickoff ASC
`

type ListUpcomingMatchesByUserParams struct {
	Cutoff time.Time
	UserID string
}

type ListUpcomingMatchesByUserRow struct {
	ID          string
	Kickoff     time.Time
	Stadium     string
	City        string
	Stage       string
	HomeID      string
	HomeName    string
	HomeFlagUrl string
	HomeCode    string
	AwayID      string
	AwayName    string
	AwayFlagUrl string
	AwayCode    string
}

func (q *Queries) ListUpcomingMatchesByUser(ctx context.Context, arg ListUpcomingMatchesByUserParams) ([]ListUpcomingMatchesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingMatchesByUser, arg.Cutoff, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingMatchesByUserRow
	for rows.Next() {
		var i ListUpcomingMatchesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Kickoff,
			&i.Stadium,
			&i.City,
			&i.Stage,
			&i.HomeID,
			&i.HomeName,
			&i.HomeFlagUrl,
			&i.HomeCode,
			&i.AwayID,
			&i.AwayName,
			&i.AwayFlagUrl,
			&i.AwayCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
