// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type NationalTeam struct {
	ID      string
	Name    string
	FlagUrl string
}

type User struct {
	ID           string
	FullName     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

type UserNationalTeam struct {
	UserID         string
	NationalTeamID string
}
