// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Match struct {
	ID         string
	Kickoff    time.Time
	HomeTeamID string
	AwayTeamID string
	Stadium    string
	City       string
	Stage      string
}

type NationalTeam struct {
	ID      string
	Name    string
	FlagUrl string
	Code    string
}

type User struct {
	ID                    string
	FullName              string
	Email                 string
	PasswordHash          string
	CreatedAt             time.Time
	TempPasswordHash      sql.NullString
	TempPasswordExpiresAt sql.NullTime
}

type UserNationalTeam struct {
	UserID         string
	NationalTeamID string
}
