// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: national_teams.sql

package sqlc

import (
	"context"
)

const getNationalTeamByID = `-- name: GetNationalTeamByID :one
SELECT id, name, flag_url, code
FROM national_teams
WHERE id = ?
`

func (q *Queries) GetNationalTeamByID(ctx context.Context, id string) (NationalTeam, error) {
	row := q.db.QueryRowContext(ctx, getNationalTeamByID, id)
	var i NationalTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FlagUrl,
		&i.Code,
	)
	return i, err
}

const listNationalTeams = `-- name: ListNationalTeams :many
SELECT id, name, flag_url, code
FROM national_teams
ORDER BY name
`

func (q *Queries) ListNationalTeams(ctx context.Context) ([]NationalTeam, error) {
	rows, err := q.db.QueryContext(ctx, listNationalTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NationalTeam
	for rows.Next() {
		var i NationalTeam
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FlagUrl,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
