// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const addUserNationalTeam = `-- name: AddUserNationalTeam :exec
INSERT INTO user_national_teams (user_id, national_team_id)
VALUES (?, ?)
`

type AddUserNationalTeamParams struct {
	UserID         string
	NationalTeamID string
}

func (q *Queries) AddUserNationalTeam(ctx context.Context, arg AddUserNationalTeamParams) error {
	_, err := q.db.ExecContext(ctx, addUserNationalTeam, arg.UserID, arg.NationalTeamID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, full_name, email, password_hash)
VALUES (?, ?, ?, ?)
RETURNING id, full_name, email, password_hash, created_at
`

type CreateUserParams struct {
	ID           string
	FullName     string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, password_hash, created_at
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, email, password_hash, created_at
FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listUserNationalTeams = `-- name: ListUserNationalTeams :many
SELECT national_team_id
FROM user_national_teams
WHERE user_id = ?
`

func (q *Queries) ListUserNationalTeams(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserNationalTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var national_team_id string
		if err := rows.Scan(&national_team_id); err != nil {
			return nil, err
		}
		items = append(items, national_team_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
