syntax = "proto3";

package wc2026.auth.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/rodrigorahman/wc_2026_api/gen/wc2026/auth/v1;authv1";

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc GetMe(GetMeRequest) returns (GetMeResponse);
  rpc RequestPasswordRecovery(RequestPasswordRecoveryRequest) returns (RequestPasswordRecoveryResponse);
  rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);
}

message RegisterRequest {
  string full_name = 1 [(buf.validate.field).string = {
    min_len: 1
  }];
  string email = 2 [(buf.validate.field).string.email = true];
  string password = 3 [(buf.validate.field).string = {
    min_len: 8
  }];
  repeated string national_team_ids = 4 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 3
    items: {
      string: {uuid: true}
    }
  }];
}

message RegisterResponse {
  string user_id = 1;
}

message LoginRequest {
  string email = 1 [(buf.validate.field).string.email = true];
  string password = 2 [(buf.validate.field).string = {
    min_len: 1
  }];
}

message LoginResponse {
  string access_token = 1;
  google.protobuf.Timestamp expires_at = 2;
  bool password_change_required = 3;
}

message GetMeRequest {}

message GetMeResponse {
  string user_id = 1;
  string full_name = 2;
  string email = 3;
  repeated string national_team_ids = 4;
}

message RequestPasswordRecoveryRequest {
  string email = 1 [(buf.validate.field).string.email = true];
}

message RequestPasswordRecoveryResponse {
  string message = 1;
}

message ChangePasswordRequest {
  string temp_password = 1 [(buf.validate.field).string = { min_len: 1 }];
  string new_password  = 2 [(buf.validate.field).string = { min_len: 8 }];
}

message ChangePasswordResponse {}
